// Package manager types
export type PackageManager = 'npm' | 'yarn' | 'pnpm';

// Test profile options for configurable testing setup
export type TestProfile = 'bare' | 'minimum' | 'standard' | 'advanced' | 'complete';

// Test profile configuration
export interface TestProfileConfig {
  name: string;
  description: string;
  coverage: number;
  testTypes: Array<
    | 'unit'
    | 'integration'
    | 'accessibility'
    | 'performance'
    | 'snapshot'
    | 'redux'
    | 'router'
    | 'i18n'
    | 'tailwind'
  >;
  dependencies: string[];
}

// Feature flags for modular template composition
export interface FeatureFlags {
  typescript: boolean;
  tailwindcss: boolean;
  redux: boolean;
  reactRouter: boolean;
  i18n: boolean; // react-i18next internationalization
  eslint: boolean;
  prettier: boolean;
  husky: boolean;
  githubActions: boolean;
  vscode: boolean;
  testing: boolean;
  testProfile?: TestProfile;
}

// ============================================================================
// DYNAMIC TEMPLATE SYSTEM TYPES
// ============================================================================

// Technology icons for showcase display
export interface TechIcon {
  name: string;
  logo: string; // SVG filename or inline SVG
  url: string;
  color: string;
}

// Feature card configuration for showcase App
export interface FeatureCard {
  id: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  feature: keyof FeatureFlags; // Which feature flag enables this card
}

// Component registry for dynamic composition
export interface ComponentRegistry {
  providers: ProviderConfig[];
  cards: FeatureCard[];
  icons: TechIcon[];
}

// Provider wrapper configuration (for main.tsx)
export interface ProviderConfig {
  name: string;
  feature: keyof FeatureFlags;
  importStatement: string;
  wrapperStart: string;
  wrapperEnd: string;
  order: number; // Lower = outer wrapper (i18n=1, redux=2, router=3)
}

// Translation keys structure for i18n
export interface TranslationKeys {
  hero: {
    title: string;
    subtitle: string;
  };
  features: {
    counter: { title: string; description: string };
    redux: { title: string; description: string };
    router: { title: string; description: string };
    i18n: { title: string; description: string };
  };
  footer: {
    madeWith: string;
    by: string;
  };
  common: {
    increment: string;
    lightMode: string;
    darkMode: string;
    language: string;
  };
}

// Base packages always included
export type BasePackage = 'react' | 'react-dom' | 'vite';

// Optional feature packages
export type FeaturePackage =
  | 'tailwindcss'
  | '@tailwindcss/vite'
  | '@reduxjs/toolkit'
  | 'react-redux'
  | 'react-router-dom';

// Dev packages
export type DevPackage =
  | 'typescript'
  | '@types/react'
  | '@types/react-dom'
  | '@types/node'
  | '@vitejs/plugin-react'
  | 'eslint'
  | '@eslint/js'
  | '@typescript-eslint/eslint-plugin'
  | '@typescript-eslint/parser'
  | 'typescript-eslint'
  | 'eslint-plugin-react-hooks'
  | 'eslint-plugin-react-refresh'
  | 'eslint-config-prettier'
  | 'eslint-plugin-prettier'
  | 'prettier'
  | 'globals'
  | 'husky'
  | 'lint-staged'
  | 'vitest'
  | '@vitest/coverage-v8'
  | '@vitest/ui'
  | '@testing-library/react'
  | '@testing-library/jest-dom'
  | '@testing-library/user-event'
  | 'jsdom';

// Template definition
export interface Template {
  id: string;
  name: string;
  description: string;
  features: FeatureFlags;
  icon: string;
  color: string;
}

// Project configuration from user input
export interface ProjectConfig {
  name: string;
  author: string;
  license: string;
  description: string;
  template: Template;
  features: FeatureFlags;
  packageManager: PackageManager;
  initGit: boolean;
  installDeps: boolean;
  targetDir: string;
}

// CLI state for multi-step wizard
export type WizardStep =
  | 'welcome'
  | 'project-name'
  | 'template-select'
  | 'feature-select'
  | 'test-profile-select'
  | 'package-manager'
  | 'git-init'
  | 'summary'
  | 'creating'
  | 'complete'
  | 'error';

export interface WizardState {
  step: WizardStep;
  config: Partial<ProjectConfig>;
  error?: string;
}

// Dependency versions for package.json generation
export interface DependencyVersions {
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
}

// ============================================================================
// PLUGIN SYSTEM TYPES
// ============================================================================

/**
 * PluginContext - Context available to plugins during file generation
 */
export interface PluginContext {
  features: FeatureFlags;
  projectName: string;
  author: string;
  description: string;
  license: string;
  targetDir: string;
  packageManager: PackageManager;
}

/**
 * PluginFile - A file to be generated by a plugin
 */
export interface PluginFile {
  /** Relative path from project root (e.g., 'src/store/store.ts') */
  path: string;
  /** File content (can be a template string or raw content) */
  content: string;
  /** Whether content is a Handlebars template that needs processing */
  isTemplate?: boolean;
}

/**
 * Plugin - Interface for feature plugins
 *
 * Plugins encapsulate all logic for a specific feature:
 * - File generation
 * - Dependencies
 * - Configuration
 */
export interface Plugin {
  /** Unique plugin identifier (should match feature flag key) */
  id: keyof FeatureFlags | string;

  /** Human-readable plugin name */
  name: string;

  /** Plugin description */
  description?: string;

  /** Order in which plugin runs (lower = earlier) */
  order?: number;

  /**
   * Check if this plugin should be active based on features
   * @param features Current feature flags
   * @returns true if plugin should run
   */
  shouldActivate: (features: FeatureFlags) => boolean;

  /**
   * Get files to generate for this plugin
   * @param context Plugin context with project info
   * @returns Array of files to generate
   */
  getFiles: (context: PluginContext) => Promise<PluginFile[]>;

  /**
   * Get runtime dependencies for this plugin
   * @param context Plugin context (optional)
   * @returns Record of package name to version
   */
  getDependencies: (context?: PluginContext) => Record<string, string>;

  /**
   * Get dev dependencies for this plugin
   * @param context Plugin context (optional)
   * @returns Record of package name to version
   */
  getDevDependencies: (context?: PluginContext) => Record<string, string>;

  /**
   * Get scripts to add to package.json
   * @param context Plugin context (optional)
   * @returns Record of script name to command
   */
  getScripts?: (context?: PluginContext) => Record<string, string>;

  /**
   * Get setup commands to run after file generation
   * @returns Array of shell commands
   */
  getSetupCommands?: () => string[];

  /**
   * Hook called after all files are generated
   * Can be used for post-processing or validation
   */
  afterGenerate?: (context: PluginContext) => Promise<void>;
}

/**
 * PluginRegistry - Manages available plugins
 */
export interface PluginRegistry {
  /** Register a plugin */
  register: (plugin: Plugin) => void;

  /** Get all registered plugins */
  getAll: () => Plugin[];

  /** Get plugins that should be active for given features */
  getActive: (features: FeatureFlags) => Plugin[];

  /** Get a plugin by ID */
  get: (id: string) => Plugin | undefined;
}
