import type { Plugin, PluginContext, PluginFile } from '../types/index.js';
import { featureDependencies, featureDevDependencies } from '../config/dependencies.js';

/**
 * i18n Plugin
 *
 * Generates react-i18next configuration and translation files
 */
export const i18nPlugin: Plugin = {
  id: 'i18n',
  name: 'Internationalization',
  description: 'Multi-language support with react-i18next',
  order: 15,

  shouldActivate: features => Boolean(features.i18n),

  async getFiles(_context: PluginContext): Promise<PluginFile[]> {
    return [
      {
        path: 'src/i18n/config.ts',
        content: `import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

import en from './locales/en.json';
import pt from './locales/pt.json';
import es from './locales/es.json';

const resources = {
  en: { translation: en },
  pt: { translation: pt },
  es: { translation: es },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: import.meta.env.DEV,
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag'],
      caches: ['localStorage'],
    },
  });

export default i18n;
`,
      },
      {
        path: 'src/i18n/locales/en.json',
        content: JSON.stringify(
          {
            hero: {
              title: 'React + Vite Starter',
              subtitle: 'A modern starting point for your React projects',
            },
            features: {
              counter: { title: 'useState Hook', description: 'Click to increment' },
              timer: { title: 'useEffect Hook', description: 'Auto-incrementing timer' },
              redux: { title: 'Redux Theme', description: 'Theme managed by Redux' },
              router: { title: 'React Router', description: 'Navigate between pages' },
              i18n: { title: 'Internationalization', description: 'Switch languages' },
            },
            pages: {
              about: {
                title: 'About This Project',
                description:
                  'This showcase app was generated by react-vite-starter-kit, demonstrating all the features you selected during setup.',
              },
            },
            common: {
              increment: 'Increment',
              start: 'Start',
              stop: 'Stop',
              reset: 'Reset',
              lightMode: 'Light',
              darkMode: 'Dark',
              currentTheme: 'Current theme',
              home: 'Home',
              about: 'About',
            },
            footer: { madeWith: 'Made with ❤️ by' },
          },
          null,
          2
        ),
      },
      {
        path: 'src/i18n/locales/pt.json',
        content: JSON.stringify(
          {
            hero: {
              title: 'React + Vite Starter',
              subtitle: 'Um ponto de partida moderno para seus projetos React',
            },
            features: {
              counter: { title: 'Hook useState', description: 'Clique para incrementar' },
              timer: { title: 'Hook useEffect', description: 'Temporizador auto-incrementante' },
              redux: { title: 'Tema Redux', description: 'Tema gerenciado pelo Redux' },
              router: { title: 'React Router', description: 'Navegue entre páginas' },
              i18n: { title: 'Internacionalização', description: 'Alterne idiomas' },
            },
            pages: {
              about: {
                title: 'Sobre Este Projeto',
                description:
                  'Este aplicativo de demonstração foi gerado pelo react-vite-starter-kit, demonstrando todos os recursos que você selecionou durante a configuração.',
              },
            },
            common: {
              increment: 'Incrementar',
              start: 'Iniciar',
              stop: 'Parar',
              reset: 'Resetar',
              lightMode: 'Claro',
              darkMode: 'Escuro',
              currentTheme: 'Tema atual',
              home: 'Início',
              about: 'Sobre',
            },
            footer: { madeWith: 'Feito com ❤️ por' },
          },
          null,
          2
        ),
      },
      {
        path: 'src/i18n/locales/es.json',
        content: JSON.stringify(
          {
            hero: {
              title: 'React + Vite Starter',
              subtitle: 'Un punto de partida moderno para tus proyectos React',
            },
            features: {
              counter: { title: 'Hook useState', description: 'Haz clic para incrementar' },
              timer: { title: 'Hook useEffect', description: 'Temporizador auto-incrementante' },
              redux: { title: 'Tema Redux', description: 'Tema gestionado por Redux' },
              router: { title: 'React Router', description: 'Navega entre páginas' },
              i18n: { title: 'Internacionalización', description: 'Cambia idiomas' },
            },
            pages: {
              about: {
                title: 'Sobre Este Proyecto',
                description:
                  'Esta aplicación de demostración fue generada por react-vite-starter-kit, demostrando todas las características que seleccionaste durante la configuración.',
              },
            },
            common: {
              increment: 'Incrementar',
              start: 'Iniciar',
              stop: 'Detener',
              reset: 'Reiniciar',
              lightMode: 'Claro',
              darkMode: 'Oscuro',
              currentTheme: 'Tema actual',
              home: 'Inicio',
              about: 'Acerca',
            },
            footer: { madeWith: 'Hecho con ❤️ por' },
          },
          null,
          2
        ),
      },
    ];
  },

  getDependencies: () => featureDependencies.i18n || {},

  getDevDependencies: () => featureDevDependencies.i18n || {},
};

export default i18nPlugin;
